__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"../../bin/daemon.elf\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"../../bin/util.elf\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global store_png_start\n"
        ".type   store_png_start, @object\n"
        ".align  16\n"
        "store_png_start:\n"
        ".incbin \"assets/store.png\"\n"
        "store_png_end:\n"
        ".global store_png_size\n"
        ".type   store_png_size, @object\n"
        ".align  4\n"
        "store_png_size:\n"
        ".int    store_png_end - store_png_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"assets/etahen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"
       
        ".global webman_icon_start\n"
        ".type   webman_icon_start,"
        "@object\n"
        ".align  16\n"
        "webman_icon_start:\n"
        ".incbin \"assets/webMAN.png\"\n"
        "webman_icon_end:\n"
        ".global webman_icon_size\n"
        ".type   webman_icon_size, @object\n"
        ".align  4\n"
        "webman_icon_size:\n"
        ".int    webman_icon_end - webman_icon_start\n"

    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"assets/kstuff.elf\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"

    ".global fps_prx_start\n"
    ".type   fps_prx_start, @object\n"
    ".align  16\n"
    "fps_prx_start:\n"
    ".incbin \"assets/fps.prx\"\n"
    "fps_prx_end:\n"
    ".global fps_prx_size\n"
    ".type  fps_prx_size, @object\n"
    ".align  4\n"
    "fps_prx_size:\n"
    ".int    fps_prx_end - fps_prx_start\n"
);
