/* Autogenerated by hxtools bin2c */
#ifndef HEN_H
#define HEN_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern uint8_t KELF[];
extern uint64_t KELF_SZ;

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* HEN_H */
