__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"../../bin/daemon.elf\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"../../bin/util.elf\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global store_png_start\n"
        ".type   store_png_start, @object\n"
        ".align  16\n"
        "store_png_start:\n"
        ".incbin \"assets/store.png\"\n"
        "store_png_end:\n"
        ".global store_png_size\n"
        ".type   store_png_size, @object\n"
        ".align  4\n"
        "store_png_size:\n"
        ".int    store_png_end - store_png_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"assets/etahen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"
       
        ".global webman_icon_start\n"
        ".type   webman_icon_start,"
        "@object\n"
        ".align  16\n"
        "webman_icon_start:\n"
        ".incbin \"assets/webMAN.png\"\n"
        "webman_icon_end:\n"
        ".global webman_icon_size\n"
        ".type   webman_icon_size, @object\n"
        ".align  4\n"
        "webman_icon_size:\n"
        ".int    webman_icon_end - webman_icon_start\n"

    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"assets/kstuff.elf\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"

    ".global fps_prx_start\n"
    ".type   fps_prx_start, @object\n"
    ".align  16\n"
    "fps_prx_start:\n"
    ".incbin \"assets/fps.prx\"\n"
    "fps_prx_end:\n"
    ".global fps_prx_size\n"
    ".type  fps_prx_size, @object\n"
    ".align  4\n"
    "fps_prx_size:\n"
    ".int    fps_prx_end - fps_prx_start\n"

    // L92 Edition toolbox icons (written to /data/etaHEN/assets/l92_icons/)
    ".global l92_main_png_start\n"
    ".type   l92_main_png_start, @object\n"
    ".align  16\n"
    "l92_main_png_start:\n"
    ".incbin \"assets/l92_icons/L92_main.png\"\n"
    "l92_main_png_end:\n"
    ".global l92_main_png_size\n"
    ".type  l92_main_png_size, @object\n"
    ".align  4\n"
    "l92_main_png_size:\n"
    ".int    l92_main_png_end - l92_main_png_start\n"

    ".global l92_pkg_png_start\n"
    ".type   l92_pkg_png_start, @object\n"
    ".align  16\n"
    "l92_pkg_png_start:\n"
    ".incbin \"assets/l92_icons/L92_pkg.png\"\n"
    "l92_pkg_png_end:\n"
    ".global l92_pkg_png_size\n"
    ".type  l92_pkg_png_size, @object\n"
    ".align  4\n"
    "l92_pkg_png_size:\n"
    ".int    l92_pkg_png_end - l92_pkg_png_start\n"

    ".global l92_plugins_png_start\n"
    ".type   l92_plugins_png_start, @object\n"
    ".align  16\n"
    "l92_plugins_png_start:\n"
    ".incbin \"assets/l92_icons/L92_plugins.png\"\n"
    "l92_plugins_png_end:\n"
    ".global l92_plugins_png_size\n"
    ".type  l92_plugins_png_size, @object\n"
    ".align  4\n"
    "l92_plugins_png_size:\n"
    ".int    l92_plugins_png_end - l92_plugins_png_start\n"

    ".global l92_cheats_png_start\n"
    ".type   l92_cheats_png_start, @object\n"
    ".align  16\n"
    "l92_cheats_png_start:\n"
    ".incbin \"assets/l92_icons/L92_cheats.png\"\n"
    "l92_cheats_png_end:\n"
    ".global l92_cheats_png_size\n"
    ".type  l92_cheats_png_size, @object\n"
    ".align  4\n"
    "l92_cheats_png_size:\n"
    ".int    l92_cheats_png_end - l92_cheats_png_start\n"

    ".global l92_remote_png_start\n"
    ".type   l92_remote_png_start, @object\n"
    ".align  16\n"
    "l92_remote_png_start:\n"
    ".incbin \"assets/l92_icons/L92_remote.png\"\n"
    "l92_remote_png_end:\n"
    ".global l92_remote_png_size\n"
    ".type  l92_remote_png_size, @object\n"
    ".align  4\n"
    "l92_remote_png_size:\n"
    ".int    l92_remote_png_end - l92_remote_png_start\n"

    ".global l92_services_png_start\n"
    ".type   l92_services_png_start, @object\n"
    ".align  16\n"
    "l92_services_png_start:\n"
    ".incbin \"assets/l92_icons/L92_services.png\"\n"
    "l92_services_png_end:\n"
    ".global l92_services_png_size\n"
    ".type  l92_services_png_size, @object\n"
    ".align  4\n"
    "l92_services_png_size:\n"
    ".int    l92_services_png_end - l92_services_png_start\n"

    ".global l92_settings_png_start\n"
    ".type   l92_settings_png_start, @object\n"
    ".align  16\n"
    "l92_settings_png_start:\n"
    ".incbin \"assets/l92_icons/L92_settings.png\"\n"
    "l92_settings_png_end:\n"
    ".global l92_settings_png_size\n"
    ".type  l92_settings_png_size, @object\n"
    ".align  4\n"
    "l92_settings_png_size:\n"
    ".int    l92_settings_png_end - l92_settings_png_start\n"

    ".global l92_kstuff_png_start\n"
    ".type   l92_kstuff_png_start, @object\n"
    ".align  16\n"
    "l92_kstuff_png_start:\n"
    ".incbin \"assets/l92_icons/L92_kstuff.png\"\n"
    "l92_kstuff_png_end:\n"
    ".global l92_kstuff_png_size\n"
    ".type  l92_kstuff_png_size, @object\n"
    ".align  4\n"
    "l92_kstuff_png_size:\n"
    ".int    l92_kstuff_png_end - l92_kstuff_png_start\n"

    ".global l92_games_png_start\n"
    ".type   l92_games_png_start, @object\n"
    ".align  16\n"
    "l92_games_png_start:\n"
    ".incbin \"assets/l92_icons/L92_games.png\"\n"
    "l92_games_png_end:\n"
    ".global l92_games_png_size\n"
    ".type  l92_games_png_size, @object\n"
    ".align  4\n"
    "l92_games_png_size:\n"
    ".int    l92_games_png_end - l92_games_png_start\n"

    ".global l92_store_png_start\n"
    ".type   l92_store_png_start, @object\n"
    ".align  16\n"
    "l92_store_png_start:\n"
    ".incbin \"assets/l92_icons/L92_store.png\"\n"
    "l92_store_png_end:\n"
    ".global l92_store_png_size\n"
    ".type  l92_store_png_size, @object\n"
    ".align  4\n"
    "l92_store_png_size:\n"
    ".int    l92_store_png_end - l92_store_png_start\n"

    ".global l92_testkit_png_start\n"
    ".type   l92_testkit_png_start, @object\n"
    ".align  16\n"
    "l92_testkit_png_start:\n"
    ".incbin \"assets/l92_icons/L92_testkit.png\"\n"
    "l92_testkit_png_end:\n"
    ".global l92_testkit_png_size\n"
    ".type  l92_testkit_png_size, @object\n"
    ".align  4\n"
    "l92_testkit_png_size:\n"
    ".int    l92_testkit_png_end - l92_testkit_png_start\n"

    ".global l92_shortcuts_png_start\n"
    ".type   l92_shortcuts_png_start, @object\n"
    ".align  16\n"
    "l92_shortcuts_png_start:\n"
    ".incbin \"assets/l92_icons/L92_shortcuts.png\"\n"
    "l92_shortcuts_png_end:\n"
    ".global l92_shortcuts_png_size\n"
    ".type  l92_shortcuts_png_size, @object\n"
    ".align  4\n"
    "l92_shortcuts_png_size:\n"
    ".int    l92_shortcuts_png_end - l92_shortcuts_png_start\n"

    ".global l92_about_png_start\n"
    ".type   l92_about_png_start, @object\n"
    ".align  16\n"
    "l92_about_png_start:\n"
    ".incbin \"assets/l92_icons/L92_about.png\"\n"
    "l92_about_png_end:\n"
    ".global l92_about_png_size\n"
    ".type  l92_about_png_size, @object\n"
    ".align  4\n"
    "l92_about_png_size:\n"
    ".int    l92_about_png_end - l92_about_png_start\n"
);
